---
- name: install ntp
  apt: name={{ item }} update_cache=yes
  with_items:
    - ntp
- name: Update /etc/ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntp service
- name: Delete ntp.conf.dhcp
  file: name=/var/lib/ntp/ntp.conf.dhcp state=absent
  